### ISSUE TITLE
Review SDHCI description on Armada 385 in mainline

### ISSUE THREAD

**Issue by tpetazzoni** [MISL-EBU-System-SW/mainline-public#60]
Several things:

- armada-385-rd.dts in mainline doesn't have a sdhci description, but it does in the LSP.
- Make sure we have no-1-8-v everywhere in Armada 38x DTS for sdhci
- Look if the wp-inverted property really makes sense

**Comment by gclement** [comment]
* SDHCI descritpion for Armada 38x RD submitted: http://thread.gmane.org/gmane.linux.kernel.mmc/30729
* no-1-8-v is everywhere on the  Armada 38x DTS for sdhci
* wp-inverted is mandatory when no gpio is used for WP, because the value of the Write Protect bit(bit 19) in the Present State register (0x24) of the sdhci is always 0 which according to the SD card sepc means "Write protected"
